name: note build
# 触发workflow的条件
on:
  push:
    # 只有main分支发生push事件时，才会触发workflow
    branches: [main]

jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: centos # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@main
      # 上传打包资源
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_USER }}
          connect_timeout: 60s
          last_ssh: |
            cd /usr/local/test/chatgpt_server
            git checkout .
            git pull
            npm install
            pm2 delete anygpt_server
            pm2 start index.js --name anygpt_server
